(cl:in-package beta_nodes-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEG_TYPE-VAL
          SEG_TYPE
          PRIORITY-VAL
          PRIORITY
          SEG_NUMBER-VAL
          SEG_NUMBER
          SEG_LENGTH-VAL
          SEG_LENGTH
          INIT_POINT-VAL
          INIT_POINT
          REF_POINT-VAL
          REF_POINT
          INIT_TAN_ANGLE-VAL
          INIT_TAN_ANGLE
          SEG_PSI-VAL
          SEG_PSI
          CURVATURE-VAL
          CURVATURE
          MAX_SPEEDS-VAL
          MAX_SPEEDS
          MIN_SPEEDS-VAL
          MIN_SPEEDS
          ACCEL_LIMIT-VAL
          ACCEL_LIMIT
          DECEL_LIMIT-VAL
          DECEL_LIMIT
))