global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 1.0

publish_voxel_map: true

static_map: true

rolling_window: false
width: 6.0
height: 6.0
resolution: 0.1

map_type: costmap
origin_z: 0.0
z_resolution: 0.2
z_voxels: 60
unknown_threshold: 10
mark_threshold: 1

transform_tolerance: 0.03
obstacle_range: 15.0
max_obstacle_height: 4.0
raytrace_range: 12.0
footprint: [[0.3048, 0.3048], [0.3048, -0.3048], [-0.711, -0.3048], [-0.711, 0.3048]]

footprint_padding: 0.01
inflation_radius: 0.36
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
observation_sources: base_laser1_scan kinect
base_laser1_scan: {sensor_frame: base_laser1_link_ignore, data_type: LaserScan, topic: base_laser1_scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 3.0, observation_persistence: 0.1}
kinect: {sensor_frame: camera_depth_optical_frame_ignore, data_type: PointCloud2, topic: camera/depth/points, min_obstacle_height: 0.05, max_obstacle_height: 1.0, marking: true, clearing: true, observation_persistence: 0.1}
