/* Auto-generated by genmsg_cpp for file /home/albireo/code/dev_stacks/EECS376/steering/msg/obstacle.msg */
#ifndef STEERING_MESSAGE_OBSTACLE_H
#define STEERING_MESSAGE_OBSTACLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace steering
{
template <class ContainerAllocator>
struct obstacle_ {
  typedef obstacle_<ContainerAllocator> Type;

  obstacle_()
  : header()
  , nearestObstacle(0.0)
  , nearestTheta(0)
  , obstacle(false)
  {
  }

  obstacle_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , nearestObstacle(0.0)
  , nearestTheta(0)
  , obstacle(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _nearestObstacle_type;
  float nearestObstacle;

  typedef uint8_t _nearestTheta_type;
  uint8_t nearestTheta;

  typedef uint8_t _obstacle_type;
  uint8_t obstacle;

  static const float boxWidth;
  static const float boxLength;

private:
  static const char* __s_getDataType_() { return "steering/obstacle"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4b4e1755df273bbeb9038b63e3e0a9be"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 boxWidth = 0.2\n\
float32 boxLength =1.6\n\
float32 nearestObstacle\n\
uint8 nearestTheta\n\
bool obstacle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, nearestObstacle);
    ros::serialization::serialize(stream, nearestTheta);
    ros::serialization::serialize(stream, obstacle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, nearestObstacle);
    ros::serialization::deserialize(stream, nearestTheta);
    ros::serialization::deserialize(stream, obstacle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(nearestObstacle);
    size += ros::serialization::serializationLength(nearestTheta);
    size += ros::serialization::serializationLength(obstacle);
    return size;
  }

  typedef boost::shared_ptr< ::steering::obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::obstacle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct obstacle
typedef  ::steering::obstacle_<std::allocator<void> > obstacle;

typedef boost::shared_ptr< ::steering::obstacle> obstaclePtr;
typedef boost::shared_ptr< ::steering::obstacle const> obstacleConstPtr;

template<typename ContainerAllocator> const float obstacle_<ContainerAllocator>::boxWidth = 0.2;
template<typename ContainerAllocator> const float obstacle_<ContainerAllocator>::boxLength = 1.6;

template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::steering::obstacle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::steering::obstacle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace steering

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::steering::obstacle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::steering::obstacle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::steering::obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4b4e1755df273bbeb9038b63e3e0a9be";
  }

  static const char* value(const  ::steering::obstacle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4b4e1755df273bbeULL;
  static const uint64_t static_value2 = 0xb9038b63e3e0a9beULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "steering/obstacle";
  }

  static const char* value(const  ::steering::obstacle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::steering::obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 boxWidth = 0.2\n\
float32 boxLength =1.6\n\
float32 nearestObstacle\n\
uint8 nearestTheta\n\
bool obstacle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::steering::obstacle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::steering::obstacle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::steering::obstacle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::steering::obstacle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.nearestObstacle);
    stream.next(m.nearestTheta);
    stream.next(m.obstacle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct obstacle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::steering::obstacle_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nearestObstacle: ";
    Printer<float>::stream(s, indent + "  ", v.nearestObstacle);
    s << indent << "nearestTheta: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nearestTheta);
    s << indent << "obstacle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_OBSTACLE_H

