/* Auto-generated by genmsg_cpp for file /home/jinx/ROSCode/beta_nodes/msg/estopMsg.msg */
#ifndef BETA_NODES_MESSAGE_ESTOPMSG_H
#define BETA_NODES_MESSAGE_ESTOPMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace beta_nodes
{
template <class ContainerAllocator>
struct estopMsg_ {
  typedef estopMsg_<ContainerAllocator> Type;

  estopMsg_()
  : Header()
  , isEstopped(false)
  {
  }

  estopMsg_(const ContainerAllocator& _alloc)
  : Header(_alloc)
  , isEstopped(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
   ::std_msgs::Header_<ContainerAllocator>  Header;

  typedef uint8_t _isEstopped_type;
  uint8_t isEstopped;


private:
  static const char* __s_getDataType_() { return "beta_nodes/estopMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "89970523909eb9ebf202b06133757daa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header Header\n\
bool isEstopped\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Header);
    ros::serialization::serialize(stream, isEstopped);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Header);
    ros::serialization::deserialize(stream, isEstopped);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Header);
    size += ros::serialization::serializationLength(isEstopped);
    return size;
  }

  typedef boost::shared_ptr< ::beta_nodes::estopMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beta_nodes::estopMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct estopMsg
typedef  ::beta_nodes::estopMsg_<std::allocator<void> > estopMsg;

typedef boost::shared_ptr< ::beta_nodes::estopMsg> estopMsgPtr;
typedef boost::shared_ptr< ::beta_nodes::estopMsg const> estopMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::beta_nodes::estopMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::beta_nodes::estopMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace beta_nodes

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::estopMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::estopMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::beta_nodes::estopMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "89970523909eb9ebf202b06133757daa";
  }

  static const char* value(const  ::beta_nodes::estopMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x89970523909eb9ebULL;
  static const uint64_t static_value2 = 0xf202b06133757daaULL;
};

template<class ContainerAllocator>
struct DataType< ::beta_nodes::estopMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beta_nodes/estopMsg";
  }

  static const char* value(const  ::beta_nodes::estopMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::beta_nodes::estopMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header Header\n\
bool isEstopped\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::beta_nodes::estopMsg_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::beta_nodes::estopMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Header);
    stream.next(m.isEstopped);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct estopMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beta_nodes::estopMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::beta_nodes::estopMsg_<ContainerAllocator> & v) 
  {
    s << indent << "Header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "isEstopped: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isEstopped);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BETA_NODES_MESSAGE_ESTOPMSG_H

