/* Auto-generated by genmsg_cpp for file /home/jinx/ROSCode/beta_nodes/msg/obstacle.msg */
#ifndef BETA_NODES_MESSAGE_OBSTACLE_H
#define BETA_NODES_MESSAGE_OBSTACLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace beta_nodes
{
template <class ContainerAllocator>
struct obstacle_ {
  typedef obstacle_<ContainerAllocator> Type;

  obstacle_()
  : header()
  , leftClearance(0.0)
  , rightClearance(0.0)
  , nearestObstacle(0.0)
  , nearestTheta(0)
  , edgeDistance(0.0)
  , edgeTheta(0)
  , firstObstacleTheta(0)
  , lastObstacleTheta(0)
  , obstacle(false)
  {
  }

  obstacle_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , leftClearance(0.0)
  , rightClearance(0.0)
  , nearestObstacle(0.0)
  , nearestTheta(0)
  , edgeDistance(0.0)
  , edgeTheta(0)
  , firstObstacleTheta(0)
  , lastObstacleTheta(0)
  , obstacle(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _leftClearance_type;
  float leftClearance;

  typedef float _rightClearance_type;
  float rightClearance;

  typedef float _nearestObstacle_type;
  float nearestObstacle;

  typedef uint8_t _nearestTheta_type;
  uint8_t nearestTheta;

  typedef float _edgeDistance_type;
  float edgeDistance;

  typedef uint8_t _edgeTheta_type;
  uint8_t edgeTheta;

  typedef uint8_t _firstObstacleTheta_type;
  uint8_t firstObstacleTheta;

  typedef uint8_t _lastObstacleTheta_type;
  uint8_t lastObstacleTheta;

  typedef uint8_t _obstacle_type;
  uint8_t obstacle;

  static const float boxWidth;
  static const float boxLength;
  static const float threatRange;

private:
  static const char* __s_getDataType_() { return "beta_nodes/obstacle"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2b6640e54f0c0b7b92e8fbb9f966bfe0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
\n\
# laswer sweeps from the right(0) to left (180)\n\
\n\
float32 boxWidth = 0.3 # HALVED. remember, robot teack is ~.56, so make this a little over half of that\n\
float32 boxLength = 1.6\n\
\n\
float32 leftClearance  # distance to ping furthest on our right (would be 180 if we checked all of them)\n\
float32 rightClearance # distance to ping furthest on our right (would be 180 if we checked all of them)\n\
float32 threatRange = 1.0 # Range inwhich if we've hit an object we need to consider replanning\n\
\n\
float32 nearestObstacle\n\
uint8 nearestTheta\n\
\n\
float32 edgeDistance\n\
uint8 edgeTheta\n\
\n\
uint8 firstObstacleTheta ##should be rightmost obstacle ping\n\
uint8 lastObstacleTheta\n\
\n\
bool obstacle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, leftClearance);
    ros::serialization::serialize(stream, rightClearance);
    ros::serialization::serialize(stream, nearestObstacle);
    ros::serialization::serialize(stream, nearestTheta);
    ros::serialization::serialize(stream, edgeDistance);
    ros::serialization::serialize(stream, edgeTheta);
    ros::serialization::serialize(stream, firstObstacleTheta);
    ros::serialization::serialize(stream, lastObstacleTheta);
    ros::serialization::serialize(stream, obstacle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, leftClearance);
    ros::serialization::deserialize(stream, rightClearance);
    ros::serialization::deserialize(stream, nearestObstacle);
    ros::serialization::deserialize(stream, nearestTheta);
    ros::serialization::deserialize(stream, edgeDistance);
    ros::serialization::deserialize(stream, edgeTheta);
    ros::serialization::deserialize(stream, firstObstacleTheta);
    ros::serialization::deserialize(stream, lastObstacleTheta);
    ros::serialization::deserialize(stream, obstacle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(leftClearance);
    size += ros::serialization::serializationLength(rightClearance);
    size += ros::serialization::serializationLength(nearestObstacle);
    size += ros::serialization::serializationLength(nearestTheta);
    size += ros::serialization::serializationLength(edgeDistance);
    size += ros::serialization::serializationLength(edgeTheta);
    size += ros::serialization::serializationLength(firstObstacleTheta);
    size += ros::serialization::serializationLength(lastObstacleTheta);
    size += ros::serialization::serializationLength(obstacle);
    return size;
  }

  typedef boost::shared_ptr< ::beta_nodes::obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beta_nodes::obstacle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct obstacle
typedef  ::beta_nodes::obstacle_<std::allocator<void> > obstacle;

typedef boost::shared_ptr< ::beta_nodes::obstacle> obstaclePtr;
typedef boost::shared_ptr< ::beta_nodes::obstacle const> obstacleConstPtr;

template<typename ContainerAllocator> const float obstacle_<ContainerAllocator>::boxWidth = 0.3;
template<typename ContainerAllocator> const float obstacle_<ContainerAllocator>::boxLength = 1.6;
template<typename ContainerAllocator> const float obstacle_<ContainerAllocator>::threatRange = 1.0;

template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::beta_nodes::obstacle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::beta_nodes::obstacle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace beta_nodes

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::obstacle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::obstacle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::beta_nodes::obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2b6640e54f0c0b7b92e8fbb9f966bfe0";
  }

  static const char* value(const  ::beta_nodes::obstacle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2b6640e54f0c0b7bULL;
  static const uint64_t static_value2 = 0x92e8fbb9f966bfe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::beta_nodes::obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beta_nodes/obstacle";
  }

  static const char* value(const  ::beta_nodes::obstacle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::beta_nodes::obstacle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# laswer sweeps from the right(0) to left (180)\n\
\n\
float32 boxWidth = 0.3 # HALVED. remember, robot teack is ~.56, so make this a little over half of that\n\
float32 boxLength = 1.6\n\
\n\
float32 leftClearance  # distance to ping furthest on our right (would be 180 if we checked all of them)\n\
float32 rightClearance # distance to ping furthest on our right (would be 180 if we checked all of them)\n\
float32 threatRange = 1.0 # Range inwhich if we've hit an object we need to consider replanning\n\
\n\
float32 nearestObstacle\n\
uint8 nearestTheta\n\
\n\
float32 edgeDistance\n\
uint8 edgeTheta\n\
\n\
uint8 firstObstacleTheta ##should be rightmost obstacle ping\n\
uint8 lastObstacleTheta\n\
\n\
bool obstacle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::beta_nodes::obstacle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::beta_nodes::obstacle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::beta_nodes::obstacle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::beta_nodes::obstacle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.leftClearance);
    stream.next(m.rightClearance);
    stream.next(m.nearestObstacle);
    stream.next(m.nearestTheta);
    stream.next(m.edgeDistance);
    stream.next(m.edgeTheta);
    stream.next(m.firstObstacleTheta);
    stream.next(m.lastObstacleTheta);
    stream.next(m.obstacle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct obstacle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beta_nodes::obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::beta_nodes::obstacle_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "leftClearance: ";
    Printer<float>::stream(s, indent + "  ", v.leftClearance);
    s << indent << "rightClearance: ";
    Printer<float>::stream(s, indent + "  ", v.rightClearance);
    s << indent << "nearestObstacle: ";
    Printer<float>::stream(s, indent + "  ", v.nearestObstacle);
    s << indent << "nearestTheta: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nearestTheta);
    s << indent << "edgeDistance: ";
    Printer<float>::stream(s, indent + "  ", v.edgeDistance);
    s << indent << "edgeTheta: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.edgeTheta);
    s << indent << "firstObstacleTheta: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.firstObstacleTheta);
    s << indent << "lastObstacleTheta: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lastObstacleTheta);
    s << indent << "obstacle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BETA_NODES_MESSAGE_OBSTACLE_H

