/* Auto-generated by genmsg_cpp for file /home/jinx/ROSCode/beta_nodes/msg/velocityMsg.msg */
#ifndef BETA_NODES_MESSAGE_VELOCITYMSG_H
#define BETA_NODES_MESSAGE_VELOCITYMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace beta_nodes
{
template <class ContainerAllocator>
struct velocityMsg_ {
  typedef velocityMsg_<ContainerAllocator> Type;

  velocityMsg_()
  : header()
  , velocity(0.0)
  {
  }

  velocityMsg_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , velocity(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _velocity_type;
  float velocity;


private:
  static const char* __s_getDataType_() { return "beta_nodes/velocityMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "f829323f183fabb3f889a576f21902c2"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 velocity # linear or angular, dependent on segment type\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(velocity);
    return size;
  }

  typedef boost::shared_ptr< ::beta_nodes::velocityMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beta_nodes::velocityMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct velocityMsg
typedef  ::beta_nodes::velocityMsg_<std::allocator<void> > velocityMsg;

typedef boost::shared_ptr< ::beta_nodes::velocityMsg> velocityMsgPtr;
typedef boost::shared_ptr< ::beta_nodes::velocityMsg const> velocityMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::beta_nodes::velocityMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::beta_nodes::velocityMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace beta_nodes

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::velocityMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::velocityMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::beta_nodes::velocityMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f829323f183fabb3f889a576f21902c2";
  }

  static const char* value(const  ::beta_nodes::velocityMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf829323f183fabb3ULL;
  static const uint64_t static_value2 = 0xf889a576f21902c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::beta_nodes::velocityMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beta_nodes/velocityMsg";
  }

  static const char* value(const  ::beta_nodes::velocityMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::beta_nodes::velocityMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 velocity # linear or angular, dependent on segment type\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::beta_nodes::velocityMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::beta_nodes::velocityMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::beta_nodes::velocityMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::beta_nodes::velocityMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct velocityMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beta_nodes::velocityMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::beta_nodes::velocityMsg_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BETA_NODES_MESSAGE_VELOCITYMSG_H

