/* Auto-generated by genmsg_cpp for file /home/jinx/ROSCode/beta_nodes/msg/vPassBack.msg */
#ifndef BETA_NODES_MESSAGE_VPASSBACK_H
#define BETA_NODES_MESSAGE_VPASSBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace beta_nodes
{
template <class ContainerAllocator>
struct vPassBack_ {
  typedef vPassBack_<ContainerAllocator> Type;

  vPassBack_()
  : header()
  , vPast(0.0)
  , posX(0.0)
  , posY(0.0)
  {
  }

  vPassBack_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , vPast(0.0)
  , posX(0.0)
  , posY(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _vPast_type;
  float vPast;

  typedef float _posX_type;
  float posX;

  typedef float _posY_type;
  float posY;


private:
  static const char* __s_getDataType_() { return "beta_nodes/vPassBack"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1287931b7788a4e822865ae2d3624897"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 vPast\n\
float32 posX\n\
float32 posY\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, vPast);
    ros::serialization::serialize(stream, posX);
    ros::serialization::serialize(stream, posY);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, vPast);
    ros::serialization::deserialize(stream, posX);
    ros::serialization::deserialize(stream, posY);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(vPast);
    size += ros::serialization::serializationLength(posX);
    size += ros::serialization::serializationLength(posY);
    return size;
  }

  typedef boost::shared_ptr< ::beta_nodes::vPassBack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beta_nodes::vPassBack_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct vPassBack
typedef  ::beta_nodes::vPassBack_<std::allocator<void> > vPassBack;

typedef boost::shared_ptr< ::beta_nodes::vPassBack> vPassBackPtr;
typedef boost::shared_ptr< ::beta_nodes::vPassBack const> vPassBackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::beta_nodes::vPassBack_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::beta_nodes::vPassBack_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace beta_nodes

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::vPassBack_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::beta_nodes::vPassBack_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::beta_nodes::vPassBack_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1287931b7788a4e822865ae2d3624897";
  }

  static const char* value(const  ::beta_nodes::vPassBack_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1287931b7788a4e8ULL;
  static const uint64_t static_value2 = 0x22865ae2d3624897ULL;
};

template<class ContainerAllocator>
struct DataType< ::beta_nodes::vPassBack_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beta_nodes/vPassBack";
  }

  static const char* value(const  ::beta_nodes::vPassBack_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::beta_nodes::vPassBack_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 vPast\n\
float32 posX\n\
float32 posY\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::beta_nodes::vPassBack_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::beta_nodes::vPassBack_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::beta_nodes::vPassBack_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::beta_nodes::vPassBack_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.vPast);
    stream.next(m.posX);
    stream.next(m.posY);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct vPassBack_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beta_nodes::vPassBack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::beta_nodes::vPassBack_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vPast: ";
    Printer<float>::stream(s, indent + "  ", v.vPast);
    s << indent << "posX: ";
    Printer<float>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<float>::stream(s, indent + "  ", v.posY);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BETA_NODES_MESSAGE_VPASSBACK_H

